#!/bin/bash
amount=0
address=107
while test $# -gt 0; do
        case "$1" in
                --amount)
                        shift
                        amount=$1
                       
                        shift
                        ;;
                --address)
                        shift
                        address=$1
                        
                        shift
                        ;;
                *)
			echo "Please Specify address and amount with --address and --amount"
                        break
                        ;;
        esac
done

if [ $amount -eq 0 ]
then
	echo "Attempted to send 0 smartcash"
	exit
elif [ $address == 107 ] 
then
	echo "No address entered"
	exit
fi

./electrum-smart daemon start 
./electrum-smart daemon load_wallet 
echo "Paying " $amount "to" $address 
./electrum-smart payto $address $amount --unsigned 
./electrum-smart daemon close_wallet 
./electrum-smart daemon stop
